services:
  nodered:
    build: nodered
    ports:
      - "1880:1880"
    environment:
      NODE_RED_HTTP_ADMIN_ROOT: false
      NODE_RED_HTTP_NODE_ROOT: false
      NODE_RED_DISABLE_EDITOR: false
  db:
    image: docker.io/postgres:16.3-alpine3.19
    environment:
      POSTGRES_PASSWORD: passwordsegreta
      POSTGRES_USER: nodered
      POSTGRES_DB: jugdb
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d:zro

volumes:
  postgres:
