services:
  nodered:
    build: nodered
    ports:
      - "1880:1880"
    environment:
      NODE_RED_HTTP_ADMIN_ROOT: false
      NODE_RED_HTTP_NODE_ROOT: false
      NODE_RED_DISABLE_EDITOR: false
      DB_IP: db
      DB_PORT: 5432
      DB_USER: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      THINGWORX_USERNAME: ${THINGWORX_USERNAME}
      THINGWORX_PASSWORD: ${THINGWORX_PASSWORD}
      MQTT_USERNAME: ${MQTT_USERNAME}
      MQTT_PASSWORD: ${MQTT_PASSWORD}
      REDIS_HOST: redis
      JWT_SECRET: ${JWT_SECRET}
  redis:
    image: docker.io/redislabs/redistimeseries:1.12.1
    ports:
      - "6379:6379"
  db:
    image: docker.io/postgres:16.3-alpine3.19
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d:zro

volumes:
  postgres:
